import React, {Fragment} from 'react';
import Head from 'next/head';
import {Home} from '../components/home/Home';

export default function Page() {
	return (
		<Fragment>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Home/>
		</Fragment>
	);
}
